### ISSUE TITLE
Not working in fabric server 1.20.1

### ISSUE THREAD

**Issue by SimonLimon** [bayi/BayisCreateSBLoot#1]
Logs dont report any usefull information, but with the same modelist I can confirm that it is working in singleplayer.
edit1: the only part not working is the zinc nugget drop actualy

**Comment by bayi** [comment]
Are u sure its Just not bad luck ?

Im also runing a fabric server and its working fine.

**Comment by bayi** [comment]
![2024-03-31_17 39 07](https://github.com/bayi/BayisCreateSBLoot/assets/3492831/f82fe231-34b2-48b2-98aa-fb00dfac4f2e)

^ This is what i got after 15 mins of AFKing at my mixed-mob husk farm on my fabric server

**Comment by Meganium97** [comment]
I'm having a similar issue. What's the drop rate for andesite? I've had multiple friends on the same server farming zombies but not a single andesite has dropped.

**Comment by Meganium97** [comment]
I've found the issue: the datapack is not loaded unless placed inside (world)/datapacks, regardless of if it was placed in the root folder of the server pack. @SimonLimon @bayi
